url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/fawwaznadzmy.github.io" # the subpath of your site, e.g. /blog
title: "Fawwaz Nadzmy" # the name of your site, e.g. ACME Corp.
logo-name: "FawwazNadzmy"

logo: "fnadz-icon.png"
welcome: "Welcome to my Journey"
position: "Senior Software Engineer"
profile-pic: "fawwaz-icon.png"
description: "Passionate and dedicated software engineer with strong problem-solving skills, an agile mindset, and a background in technology. Proven ability to navigate challenges and achieve optimal outcomes. Natural inclination for coaching and mentoring, fostering collaboration and growth in the team. Beyond technical expertise, I analyze data during my free time and indulge my creative side by designing software, websites, and apps, reflecting both technical prowess and enthusiasm for exploring new possibilities in technology."
nav-menu:
- text: // Portfolio
  url:
  permalink: /
- text: // Publication
  url: Publication
  permalink: /Publication
- text: // Certificate
  url: Certificate
  permalink: /Certificate
- text: // Blog
  url: Blog
  permalink: /Blog

certificates:
- title: "Google Advanced Data Analytics - Professional Certificate"
  platform: Google.png 
  date: "21 Feb 2024"
  credential: "https://www.credly.com/badges/047f3675-9474-486e-a461-6f27575ab0e8/public_url"
- title: "Data Analytics Essential"
  platform: Cisco.png 
  date: "3 Feb 2024"
  credential: "https://www.credly.com/badges/8ba3ef48-6a00-4383-9647-2d057b2e3f54/public_url"
- title: "Python Essential I & II"
  platform: Cisco.png 
  date: "21 Jan 2024"
  credential: "https://www.credly.com/badges/3f3b8cd8-92dd-4353-bc28-f21967e075cd/public_url"
- title: "Google Project Management - Professional Certificate"
  platform: Google.png 
  date: "9 Dec 2023"
  credential: "https://www.credly.com/badges/62c054df-6237-4792-981f-91a399d9d4ae/public_url"

publications:
- title: "Modeling and Simulation of a Tubular Linear Switched Reluctance Actuator"
  journal: "International Journal of Innovative Technology and Exploring Engineering (IJITEE)"
  year: Dec 2019
  link: "https://www.ijitee.org/portfolio-item/l109310812s219/"
- title: "Effects of driving signal waveforms on the force characteristics of a tubular linear switched reluctance actuator (T-LSRA)"
  journal: "Proceedings of Mechanical Engineering Research Day 2019"
  year: August 2019
  link: "https://www3.utem.edu.my/care/proceedings/merd19/pdf/pvii-xviii.pdf"

# use false to turn off any social media links
twitter: https://www.linkedin.com/in/fawwaz-nadzmy-420a45106/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# google analytics
google-analytics: G-WCRC1TC2V5

paginate: 5
paginate_path: "/Blog/page:num/"
# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-paginate
